name: docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

env:
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository_owner }}/vs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # metadata generation
      - name: Extract metadata (GHCR)
        id: meta-ghcr-shell
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_GHCR }}-shell
          tags: |
            type=schedule
            type=sha

      - name: Extract metadata (GHCR)
        id: meta-ghcr-jupyter
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_GHCR }}-jupyter
          tags: |
            type=schedule
            type=sha

      - name: Extract metadata (GHCR)
        id: meta-ghcr-yuuno
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_GHCR }}-yuuno
          tags: |
            type=schedule
            type=sha

      - name: Extract metadata (GHCR)
        id: meta-ghcr-max
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_GHCR }}-max
          tags: |
            type=schedule
            type=sha


      # image building
      - name: Build and push vs-shell
        id: docker-build-shell
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME_GHCR }}-shell:latest
            ${{ steps.meta-ghcr-shell.outputs.tags }}
          target: vs-shell
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push vs-jupyter
        id: docker-build-jupyter
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME_GHCR }}-jupyter:latest
            ${{ steps.meta-ghcr-jupyter.outputs.tags }}
          target: vs-jupyter
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push vs-yuuno
        id: docker-build-yuuno
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME_GHCR }}-yuuno:latest
            ${{ steps.meta-ghcr-yuuno.outputs.tags }}
          target: vs-yuuno
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push vs-max
        id: docker-build-max
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME_GHCR }}-max:latest
            ${{ steps.meta-ghcr-max.outputs.tags }}
          target: vs-max
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
