name: Publish vs-jupyter

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

env:
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository_owner }}/vs-jupyter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (GHCR)
        id: meta-ghcr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_GHCR }}
          tags: |
            type=schedule
            type=sha

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true
          push: true
          provenance: mode=max
          tags: |
            ${{ env.IMAGE_NAME_GHCR }}:latest
            ${{ steps.meta-ghcr.outputs.tags }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

